language: php

sudo: false

php:
  - 7.1
  - 7.2

branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?$/ # and versions (tags)

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - 'phpenv config-rm xdebug.ini'
  - 'echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
  - 'echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - 'wget https://github.com/phpstan/phpstan/releases/download/0.9.1/phpstan.phar'
  - 'php phpstan.phar --version'
  - 'wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar && mv php-cs-fixer-v2.phar php-cs-fixer.phar'
  - 'php php-cs-fixer.phar --version'

before_script:
  - composer install

script:
  - 'php ./vendor/bin/phpunit'
  - 'php phpstan.phar analyse -l max src'
  - 'PHP_CS_FIXER_FUTURE_MODE=1 php php-cs-fixer.phar fix --allow-risky=yes --diff --dry-run'